name: 9Router
version: 1.0.0
schema: v1

models:
  - name: Free Coding (9Router)
    provider: openai
    model: Free_Coding
    apiBase: http://localhost:20128/v1
    apiKey: sk-3f4f3387b64343ea-q6tzte-cf6fff4b
    roles:
      - chat
      - edit
      - apply
      - autocomplete